version: 2.1

orbs:
  win: circleci/windows@5.1.0

jobs:
  build-linux:
    resource_class: small
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      - run:
          name: "Update APT"
          command: "sudo apt update"

      - run:
          name: "Install pip"
          command: "sudo apt install python3-pip -y"

      - run:
          name: "Install python dependencies"
          command: "pip install -r requirements.txt pyinstaller"

      - run:
          name: "Build application"
          command: "pyinstaller --onefile main.py"

      - run:
          name: "Install GHR v0.17.0 (Linux)"
          command: |
            wget https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_linux_amd64.tar.gz -O ghr_0.17.0.tar.gz
            tar -xzf ghr_0.17.0.tar.gz
            sudo mv ghr_v0.17.0_linux_amd64/ghr /usr/local/bin/
            rm -rf ghr_0.17.0.tar.gz ghr_v0.17.0_linux_amd64

      - run:
          name: "Determine new release tag and Release Linux Build"
          command: |
            CURRENT_TAG=$(curl -sSL https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
            if [ -z "$CURRENT_TAG" ] || [ "$CURRENT_TAG" = "null" ]; then
              NEW_TAG=1
            else
              CLEAN_TAG=$(echo $CURRENT_TAG | sed 's/^v//')
              NEW_TAG=$((CLEAN_TAG + 1))
            fi
            echo "New release tag: $NEW_TAG"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} $NEW_TAG /home/circleci/project/dist/main

  build-windows:
    executor:
      name: win/default
    steps:
      - checkout

      - run:
          name: "Install python dependencies"
          shell: powershell.exe
          command: |
            pip install -r requirements.txt pyinstaller

      - run:
          name: "Build application"
          shell: powershell.exe
          command: |
            pyinstaller --onefile main.py

      - run:
          name: "Install GHR v0.17.0 and Append Windows Build"
          shell: powershell.exe
          command: |
            curl.exe -L "https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_windows_amd64.zip" -o "ghr_0.17.0.zip"
            Expand-Archive -Path "ghr_0.17.0.zip" -DestinationPath "C:\ghr" -Force
            if (!(Test-Path "C:\ghr\ghr.exe")) {
                $ghrPath = Get-ChildItem -Path "C:\ghr" -Filter "ghr.exe" -Recurse | Select-Object -First 1
                if ($ghrPath) {
                    Copy-Item -Path $ghrPath.FullName -Destination "C:\ghr\ghr.exe"
                }
            }
            $env:PATH += ";C:\ghr"
            $releaseData = Invoke-RestMethod -Uri "https://api.github.com/repos/$env:CIRCLE_PROJECT_USERNAME/$env:CIRCLE_PROJECT_REPONAME/releases/latest"
            $releaseTag = $releaseData.tag_name
            Write-Host "Latest release tag: $releaseTag"
            C:\ghr\ghr.exe -t $env:GITHUB_TOKEN -u $env:CIRCLE_PROJECT_USERNAME -r $env:CIRCLE_PROJECT_REPONAME $releaseTag "dist\main.exe"

workflows:
  release-workflow:
    jobs:
      - build-linux:
          filters:
            branches:
              only: /.*/
            paths:
              ignore:
                - README.md
      - build-windows:
          filters:
            branches:
              only: /.*/
            paths:
              ignore:
                - README.md
